name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.8"]
        tox-env: ["py38-django32", "py38-django42", "checkqa"]
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: pip install --user tox codecov coverage

      - name: Run Tests
        env:
          TOXENV: ${{ matrix.tox-env }}
        run: tox
